window.GC_DATA = window.GC_DATA || {}; window.GC_DATA.africa_me = [
{g:"Africa & ME",c:"UAE",f:"\u{1F1E6}\u{1F1EA}",r:"middleeast",n:"Amazon.ae (Souq)",url:"amazon.ae",t:"retail",traffic:"~85M/mo",fee:"15% hoa h\u1ed3ng",feat:"FBA, Prime, thanh to\u00e1n COD"},
{g:"Africa & ME",c:"UAE",f:"\u{1F1E6}\u{1F1EA}",r:"middleeast",n:"Noon.com",url:"noon.com",t:"marketplace",traffic:"~45M/mo",fee:"5-20% hoa h\u1ed3ng",feat:"Noon Express, Noon Pay, COD"},
{g:"Africa & ME",c:"UAE",f:"\u{1F1E6}\u{1F1EA}",r:"middleeast",n:"Dubizzle",url:"dubizzle.com",t:"classified",traffic:"~18M/mo",fee:"Mi\u1ec5n ph\u00ed + g\u00f3i qu\u1ea3ng c\u00e1o",feat:"Rao v\u1eb7t C2C, b\u1ea5t \u0111\u1ed9ng s\u1ea3n, xe h\u01a1i, \u0111\u1ed3 c\u0169"},
{g:"Africa & ME",c:"UAE",f:"\u{1F1E6}\u{1F1EA}",r:"middleeast",n:"Carrefour UAE",url:"carrefouruae.com",t:"retail",traffic:"~12M/mo",fee:"Kh\u00f4ng (retail)",feat:"Grocery, \u0111i\u1ec7n t\u1eed, giao nhanh"},
{g:"Africa & ME",c:"UAE",f:"\u{1F1E6}\u{1F1EA}",r:"middleeast",n:"Namshi",url:"namshi.com",t:"fashion",traffic:"~8M/mo",fee:"20-30% hoa h\u1ed3ng",feat:"Th\u1eddi trang, gi\u00e0y d\u00e9p, tr\u1ea3 h\u00e0ng mi\u1ec5n ph\u00ed"},
{g:"Africa & ME",c:"UAE",f:"\u{1F1E6}\u{1F1EA}",r:"middleeast",n:"Mumzworld",url:"mumzworld.com",t:"retail",traffic:"~3M/mo",fee:"15-25% hoa h\u1ed3ng",feat:"M\u1eb9 & b\u00e9, \u0111\u1ed3 ch\u01a1i, s\u1ea3n ph\u1ea9m an to\u00e0n"},
{g:"Africa & ME",c:"UAE",f:"\u{1F1E6}\u{1F1EA}",r:"middleeast",n:"The Luxury Closet",url:"theluxurycloset.com",t:"secondhand",traffic:"~2.5M/mo",fee:"20-35% hoa h\u1ed3ng",feat:"Luxury secondhand, x\u00e1c th\u1ef1c h\u00e0ng hi\u1ec7u"},
{g:"Africa & ME",c:"UAE",f:"\u{1F1E6}\u{1F1EA}",r:"middleeast",n:"Melltoo",url:"melltoo.com",t:"secondhand",traffic:"~500K/mo",fee:"Mi\u1ec5n ph\u00ed ng\u01b0\u1eddi b\u00e1n",feat:"Mua b\u00e1n \u0111\u1ed3 c\u0169 C2C, giao h\u00e0ng t\u00edch h\u1ee3p"},
{g:"Africa & ME",c:"UAE",f:"\u{1F1E6}\u{1F1EA}",r:"middleeast",n:"eBay (cross-border)",url:"ebay.com",t:"marketplace",traffic:"~5M/mo (UAE)",fee:"10-12% hoa h\u1ed3ng",feat:"Cross-border, \u0111\u1ea5u gi\u00e1, B2C/C2C"},
{g:"Africa & ME",c:"UAE",f:"\u{1F1E6}\u{1F1EA}",r:"middleeast",n:"Ounass",url:"ounass.com",t:"fashion",traffic:"~2M/mo",fee:"Luxury retail",feat:"Luxury fashion, giao trong ng\u00e0y, designer"},
{g:"Africa & ME",c:"UAE",f:"\u{1F1E6}\u{1F1EA}",r:"middleeast",n:"Sivvi",url:"sivvi.com",t:"fashion",traffic:"~1.5M/mo",fee:"Retail",feat:"Th\u1eddi trang, free return 14 ng\u00e0y"},
{g:"Africa & ME",c:"Saudi Arabia",f:"\u{1F1F8}\u{1F1E6}",r:"middleeast",n:"Amazon.sa",url:"amazon.sa",t:"retail",traffic:"~65M/mo",fee:"15% hoa h\u1ed3ng",feat:"FBA, Prime, tr\u1ea3 h\u00e0ng 15 ng\u00e0y"},
{g:"Africa & ME",c:"Saudi Arabia",f:"\u{1F1F8}\u{1F1E6}",r:"middleeast",n:"Noon.com SA",url:"noon.com/saudi-en",t:"marketplace",traffic:"~38M/mo",fee:"5-20% hoa h\u1ed3ng",feat:"Noon Express, thanh to\u00e1n Mada"},
{g:"Africa & ME",c:"Saudi Arabia",f:"\u{1F1F8}\u{1F1E6}",r:"middleeast",n:"Jarir Bookstore",url:"jarir.com",t:"electronics",traffic:"~15M/mo",fee:"Retail tr\u1ef1c ti\u1ebfp",feat:"\u0110i\u1ec7n t\u1eed, s\u00e1ch, v\u0103n ph\u00f2ng ph\u1ea9m"},
{g:"Africa & ME",c:"Saudi Arabia",f:"\u{1F1F8}\u{1F1E6}",r:"middleeast",n:"Extra Stores",url:"extrastores.com",t:"electronics",traffic:"~8M/mo",fee:"Retail tr\u1ef1c ti\u1ebfp",feat:"\u0110i\u1ec7n t\u1eed, gia d\u1ee5ng, l\u1eafp \u0111\u1eb7t"},
{g:"Africa & ME",c:"Saudi Arabia",f:"\u{1F1F8}\u{1F1E6}",r:"middleeast",n:"Haraj.com.sa",url:"haraj.com.sa",t:"classified",traffic:"~25M/mo",fee:"Mi\u1ec5n ph\u00ed \u0111\u0103ng",feat:"Classified C2C l\u1edbn nh\u1ea5t SA, xe, \u0111i\u1ec7n tho\u1ea1i, \u0111\u1ed3 c\u0169"},
{g:"Africa & ME",c:"Saudi Arabia",f:"\u{1F1F8}\u{1F1E6}",r:"middleeast",n:"Opensooq SA",url:"opensooq.com/sa",t:"classified",traffic:"~6M/mo",fee:"Mi\u1ec5n ph\u00ed + featured",feat:"Rao v\u1eb7t \u0111a danh m\u1ee5c, app mobile"},
{g:"Africa & ME",c:"Saudi Arabia",f:"\u{1F1F8}\u{1F1E6}",r:"middleeast",n:"Namshi SA",url:"namshi.com",t:"fashion",traffic:"~5M/mo",fee:"20-30% hoa h\u1ed3ng",feat:"Th\u1eddi trang, COD, tr\u1ea3 h\u00e0ng d\u1ec5"},
{g:"Africa & ME",c:"Saudi Arabia",f:"\u{1F1F8}\u{1F1E6}",r:"middleeast",n:"Salla",url:"salla.sa",t:"marketplace",traffic:"~4M/mo",fee:"N\u1ec1n t\u1ea3ng b\u00e1n h\u00e0ng",feat:"T\u1ea1o store online, SaaS cho seller"},
{g:"Africa & ME",c:"Saudi Arabia",f:"\u{1F1F8}\u{1F1E6}",r:"middleeast",n:"Zid",url:"zid.sa",t:"marketplace",traffic:"~2M/mo",fee:"G\u00f3i th\u00e1ng t\u1eeb 99 SAR",feat:"N\u1ec1n t\u1ea3ng TMDT cho SME Saudi"},
{g:"Africa & ME",c:"Saudi Arabia",f:"\u{1F1F8}\u{1F1E6}",r:"middleeast",n:"Nana Direct",url:"nanadirect.com",t:"retail",traffic:"~3M/mo",fee:"Retail grocery",feat:"Si\u00eau th\u1ecb online, giao nhanh 15ph\u00fat"},
{g:"Africa & ME",c:"Israel",f:"\u{1F1EE}\u{1F1F1}",r:"middleeast",n:"Yad2.co.il",url:"yad2.co.il",t:"classified",traffic:"~30M/mo",fee:"Mi\u1ec5n ph\u00ed + premium",feat:"Classified #1 Israel, BDS, xe, vi\u1ec7c l\u00e0m, \u0111\u1ed3 c\u0169"},
{g:"Africa & ME",c:"Israel",f:"\u{1F1EE}\u{1F1F1}",r:"middleeast",n:"Amazon (cross-border)",url:"amazon.com",t:"retail",traffic:"~20M/mo (IL)",fee:"V\u1eadn chuy\u1ec3n qu\u1ed1c t\u1ebf",feat:"Cross-border, Global Store, mi\u1ec5n thu\u1ebf d\u01b0\u1edbi $75"},
{g:"Africa & ME",c:"Israel",f:"\u{1F1EE}\u{1F1F1}",r:"middleeast",n:"eBay Israel",url:"ebay.co.il",t:"marketplace",traffic:"~12M/mo",fee:"10-12% hoa h\u1ed3ng",feat:"\u0110\u1ea5u gi\u00e1, cross-border, PayPal"},
{g:"Africa & ME",c:"Israel",f:"\u{1F1EE}\u{1F1F1}",r:"middleeast",n:"AliExpress IL",url:"aliexpress.com",t:"marketplace",traffic:"~15M/mo (IL)",fee:"5-8% hoa h\u1ed3ng",feat:"Gi\u00e1 r\u1ebb, ship t\u1eeb TQ, choice shipping"},
{g:"Africa & ME",c:"Israel",f:"\u{1F1EE}\u{1F1F1}",r:"middleeast",n:"Zap.co.il",url:"zap.co.il",t:"marketplace",traffic:"~18M/mo",fee:"CPC qu\u1ea3ng c\u00e1o",feat:"So s\u00e1nh gi\u00e1, reviews, deal"},
{g:"Africa & ME",c:"Israel",f:"\u{1F1EE}\u{1F1F1}",r:"middleeast",n:"KSP",url:"ksp.co.il",t:"electronics",traffic:"~10M/mo",fee:"Retail",feat:"\u0110i\u1ec7n t\u1eed, PC, linh ki\u1ec7n, gi\u00e1 t\u1ed1t"},
{g:"Africa & ME",c:"Israel",f:"\u{1F1EE}\u{1F1F1}",r:"middleeast",n:"Walla! Shops",url:"shops.walla.co.il",t:"marketplace",traffic:"~5M/mo",fee:"CPC/CPA",feat:"Marketplace t\u1ed5ng h\u1ee3p, so s\u00e1nh"},
{g:"Africa & ME",c:"Israel",f:"\u{1F1EE}\u{1F1F1}",r:"middleeast",n:"iHerb IL",url:"iherb.com",t:"retail",traffic:"~4M/mo (IL)",fee:"Cross-border",feat:"Supplements, organic, ship nhanh"},
{g:"Africa & ME",c:"Israel",f:"\u{1F1EE}\u{1F1F1}",r:"middleeast",n:"Next IL",url:"next.co.il",t:"fashion",traffic:"~2M/mo",fee:"Retail",feat:"Th\u1eddi trang UK, ship \u0111\u1ecba ph\u01b0\u01a1ng"},
{g:"Africa & ME",c:"Israel",f:"\u{1F1EE}\u{1F1F1}",r:"middleeast",n:"Terminalx",url:"terminalx.com",t:"fashion",traffic:"~3M/mo",fee:"Retail/marketplace",feat:"Th\u1eddi trang cao c\u1ea5p, local brands"},
{g:"Africa & ME",c:"Qatar",f:"\u{1F1F6}\u{1F1E6}",r:"middleeast",n:"Amazon.ae (QA)",url:"amazon.ae",t:"retail",traffic:"~5M/mo (QA)",fee:"15% + ship",feat:"Cross-border t\u1eeb UAE, Prime"},
{g:"Africa & ME",c:"Qatar",f:"\u{1F1F6}\u{1F1E6}",r:"middleeast",n:"Opensooq QA",url:"opensooq.com/qa",t:"classified",traffic:"~2M/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"Rao v\u1eb7t xe, \u0111\u1ed3 c\u0169, nh\u00e0 \u1edf"},
{g:"Africa & ME",c:"Qatar",f:"\u{1F1F6}\u{1F1E6}",r:"middleeast",n:"Mzad Qatar",url:"mzadqatar.com",t:"classified",traffic:"~800K/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"\u0110\u1ea5u gi\u00e1 & rao v\u1eb7t \u0111\u1ecba ph\u01b0\u01a1ng"},
{g:"Africa & ME",c:"Qatar",f:"\u{1F1F6}\u{1F1E6}",r:"middleeast",n:"Lulu Hypermarket QA",url:"luluhypermarket.com/qa",t:"retail",traffic:"~1.5M/mo",fee:"Retail",feat:"Grocery, gia d\u1ee5ng, giao h\u00e0ng"},
{g:"Africa & ME",c:"Qatar",f:"\u{1F1F6}\u{1F1E6}",r:"middleeast",n:"Getit.qa",url:"getit.qa",t:"classified",traffic:"~600K/mo",fee:"Mi\u1ec5n ph\u00ed/premium",feat:"Yellow pages + classified"},
{g:"Africa & ME",c:"Qatar",f:"\u{1F1F6}\u{1F1E6}",r:"middleeast",n:"Noon QA",url:"noon.com",t:"marketplace",traffic:"~3M/mo (QA)",fee:"5-20%",feat:"Ship t\u1eeb UAE, Noon Express"},
{g:"Africa & ME",c:"Qatar",f:"\u{1F1F6}\u{1F1E6}",r:"middleeast",n:"Carrefour QA",url:"carrefourqatar.com",t:"retail",traffic:"~1M/mo",fee:"Retail",feat:"Grocery online, khuy\u1ebfn m\u00e3i"},
{g:"Africa & ME",c:"Qatar",f:"\u{1F1F6}\u{1F1E6}",r:"middleeast",n:"QatarSale",url:"qatarsale.com",t:"classified",traffic:"~400K/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"Classified \u0111\u1ecba ph\u01b0\u01a1ng"},
{g:"Africa & ME",c:"Qatar",f:"\u{1F1F6}\u{1F1E6}",r:"middleeast",n:"Snoonu",url:"snoonu.com",t:"retail",traffic:"~700K/mo",fee:"Delivery fee",feat:"Super app: \u0111\u1ed3 \u0103n, grocery, mua s\u1eafm"},
{g:"Africa & ME",c:"Qatar",f:"\u{1F1F6}\u{1F1E6}",r:"middleeast",n:"Talabat QA",url:"talabat.com/qatar",t:"retail",traffic:"~2M/mo",fee:"Delivery + commission",feat:"Food & grocery delivery"},
{g:"Africa & ME",c:"Kuwait",f:"\u{1F1F0}\u{1F1FC}",r:"middleeast",n:"Opensooq KW",url:"opensooq.com/kw",t:"classified",traffic:"~4M/mo",fee:"Mi\u1ec5n ph\u00ed + featured",feat:"Classified #1 Kuwait, xe, \u0111\u1ed3 c\u0169"},
{g:"Africa & ME",c:"Kuwait",f:"\u{1F1F0}\u{1F1FC}",r:"middleeast",n:"4Sale Kuwait",url:"4sale.com.kw",t:"classified",traffic:"~3.5M/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"App classified, xe, nh\u00e0, \u0111\u1ed3 d\u00f9ng"},
{g:"Africa & ME",c:"Kuwait",f:"\u{1F1F0}\u{1F1FC}",r:"middleeast",n:"Amazon.ae (KW)",url:"amazon.ae",t:"retail",traffic:"~4M/mo (KW)",fee:"15% + int'l ship",feat:"Cross-border t\u1eeb UAE"},
{g:"Africa & ME",c:"Kuwait",f:"\u{1F1F0}\u{1F1FC}",r:"middleeast",n:"Xcite Kuwait",url:"xcite.com",t:"electronics",traffic:"~5M/mo",fee:"Retail",feat:"\u0110i\u1ec7n t\u1eed, gia d\u1ee5ng, gaming"},
{g:"Africa & ME",c:"Kuwait",f:"\u{1F1F0}\u{1F1FC}",r:"middleeast",n:"Eureka Kuwait",url:"eureka.com.kw",t:"electronics",traffic:"~1.5M/mo",fee:"Retail",feat:"\u0110i\u1ec7n t\u1eed, \u0111i\u1ec7n gia d\u1ee5ng"},
{g:"Africa & ME",c:"Kuwait",f:"\u{1F1F0}\u{1F1FC}",r:"middleeast",n:"Blink KW",url:"blink.com.kw",t:"retail",traffic:"~800K/mo",fee:"Delivery",feat:"Grocery delivery nhanh"},
{g:"Africa & ME",c:"Kuwait",f:"\u{1F1F0}\u{1F1FC}",r:"middleeast",n:"Dabdoob",url:"dabdoob.com",t:"retail",traffic:"~500K/mo",fee:"Retail",feat:"\u0110\u1ed3 ch\u01a1i, m\u1eb9 & b\u00e9"},
{g:"Africa & ME",c:"Kuwait",f:"\u{1F1F0}\u{1F1FC}",r:"middleeast",n:"Boutiqaat",url:"boutiqaat.com",t:"fashion",traffic:"~1M/mo",fee:"Marketplace",feat:"Beauty & fashion, influencer-led"},
{g:"Africa & ME",c:"Kuwait",f:"\u{1F1F0}\u{1F1FC}",r:"middleeast",n:"Noon KW",url:"noon.com",t:"marketplace",traffic:"~2M/mo (KW)",fee:"5-20%",feat:"Ship t\u1eeb UAE/SA"},
{g:"Africa & ME",c:"Kuwait",f:"\u{1F1F0}\u{1F1FC}",r:"middleeast",n:"Ali Abdulwahab",url:"aaw.com.kw",t:"retail",traffic:"~600K/mo",fee:"Retail",feat:"Department store online"},
{g:"Africa & ME",c:"Bahrain",f:"\u{1F1E7}\u{1F1ED}",r:"middleeast",n:"Amazon.ae (BH)",url:"amazon.ae",t:"retail",traffic:"~2M/mo (BH)",fee:"15% + ship",feat:"Cross-border, Prime"},
{g:"Africa & ME",c:"Bahrain",f:"\u{1F1E7}\u{1F1ED}",r:"middleeast",n:"Opensooq BH",url:"opensooq.com/bh",t:"classified",traffic:"~1M/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"Rao v\u1eb7t \u0111\u1ecba ph\u01b0\u01a1ng"},
{g:"Africa & ME",c:"Bahrain",f:"\u{1F1E7}\u{1F1ED}",r:"middleeast",n:"Noon BH",url:"noon.com",t:"marketplace",traffic:"~1.5M/mo (BH)",fee:"5-20%",feat:"Ship t\u1eeb UAE"},
{g:"Africa & ME",c:"Bahrain",f:"\u{1F1E7}\u{1F1ED}",r:"middleeast",n:"Carrefour BH",url:"carrefourbahrain.com",t:"retail",traffic:"~500K/mo",fee:"Retail",feat:"Grocery & \u0111i\u1ec7n t\u1eed"},
{g:"Africa & ME",c:"Bahrain",f:"\u{1F1E7}\u{1F1ED}",r:"middleeast",n:"LuLu BH",url:"luluhypermarket.com/bh",t:"retail",traffic:"~400K/mo",fee:"Retail",feat:"Hypermarket online"},
{g:"Africa & ME",c:"Bahrain",f:"\u{1F1E7}\u{1F1ED}",r:"middleeast",n:"Shein BH",url:"shein.com/bh",t:"fashion",traffic:"~800K/mo (BH)",fee:"Cross-border",feat:"Fast fashion gi\u00e1 r\u1ebb"},
{g:"Africa & ME",c:"Bahrain",f:"\u{1F1E7}\u{1F1ED}",r:"middleeast",n:"Talabat BH",url:"talabat.com/bahrain",t:"retail",traffic:"~600K/mo",fee:"Delivery fee",feat:"Food & grocery"},
{g:"Africa & ME",c:"Bahrain",f:"\u{1F1E7}\u{1F1ED}",r:"middleeast",n:"Jashanmal BH",url:"jashanmal.com",t:"retail",traffic:"~200K/mo",fee:"Retail",feat:"Lifestyle & gia d\u1ee5ng"},
{g:"Africa & ME",c:"Bahrain",f:"\u{1F1E7}\u{1F1ED}",r:"middleeast",n:"The Store BH",url:"thestore.com",t:"retail",traffic:"~150K/mo",fee:"Retail",feat:"Department store"},
{g:"Africa & ME",c:"Bahrain",f:"\u{1F1E7}\u{1F1ED}",r:"middleeast",n:"Mumzworld BH",url:"mumzworld.com",t:"retail",traffic:"~300K/mo (BH)",fee:"Ship t\u1eeb UAE",feat:"M\u1eb9 & b\u00e9, ship GCC"},
{g:"Africa & ME",c:"Oman",f:"\u{1F1F4}\u{1F1F2}",r:"middleeast",n:"Amazon.ae (OM)",url:"amazon.ae",t:"retail",traffic:"~2.5M/mo (OM)",fee:"15% + int'l ship",feat:"Cross-border, COD"},
{g:"Africa & ME",c:"Oman",f:"\u{1F1F4}\u{1F1F2}",r:"middleeast",n:"Opensooq OM",url:"opensooq.com/om",t:"classified",traffic:"~1.5M/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"Classified \u0111\u1ecba ph\u01b0\u01a1ng"},
{g:"Africa & ME",c:"Oman",f:"\u{1F1F4}\u{1F1F2}",r:"middleeast",n:"OLX Oman",url:"olx.com.om",t:"classified",traffic:"~800K/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"Mua b\u00e1n C2C, xe, \u0111\u1ed3 c\u0169"},
{g:"Africa & ME",c:"Oman",f:"\u{1F1F4}\u{1F1F2}",r:"middleeast",n:"Noon OM",url:"noon.com",t:"marketplace",traffic:"~1.2M/mo (OM)",fee:"5-20%",feat:"Ship t\u1eeb UAE"},
{g:"Africa & ME",c:"Oman",f:"\u{1F1F4}\u{1F1F2}",r:"middleeast",n:"LuLu Oman",url:"luluhypermarket.com/om",t:"retail",traffic:"~600K/mo",fee:"Retail",feat:"Grocery & \u0111i\u1ec7n t\u1eed"},
{g:"Africa & ME",c:"Oman",f:"\u{1F1F4}\u{1F1F2}",r:"middleeast",n:"Sharaf DG Oman",url:"oman.sharafdg.com",t:"electronics",traffic:"~400K/mo",fee:"Retail",feat:"\u0110i\u1ec7n t\u1eed, gadgets"},
{g:"Africa & ME",c:"Oman",f:"\u{1F1F4}\u{1F1F2}",r:"middleeast",n:"Carrefour OM",url:"carrefouroman.com",t:"retail",traffic:"~350K/mo",fee:"Retail",feat:"Grocery online"},
{g:"Africa & ME",c:"Oman",f:"\u{1F1F4}\u{1F1F2}",r:"middleeast",n:"Ubuy Oman",url:"ubuy.com.om",t:"marketplace",traffic:"~300K/mo",fee:"Cross-border",feat:"S\u1ea3n ph\u1ea9m qu\u1ed1c t\u1ebf"},
{g:"Africa & ME",c:"Oman",f:"\u{1F1F4}\u{1F1F2}",r:"middleeast",n:"Oman Sale",url:"omansale.com",t:"classified",traffic:"~200K/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"Classified local"},
{g:"Africa & ME",c:"Oman",f:"\u{1F1F4}\u{1F1F2}",r:"middleeast",n:"Xcite OM",url:"xcite.com",t:"electronics",traffic:"~250K/mo",fee:"Retail",feat:"\u0110i\u1ec7n t\u1eed ship t\u1eeb KW"},
{g:"Africa & ME",c:"Jordan",f:"\u{1F1EF}\u{1F1F4}",r:"middleeast",n:"Opensooq JO",url:"opensooq.com/jo",t:"classified",traffic:"~8M/mo",fee:"Mi\u1ec5n ph\u00ed + featured",feat:"Classified #1 Jordan, r\u1ea5t ph\u1ed5 bi\u1ebfn"},
{g:"Africa & ME",c:"Jordan",f:"\u{1F1EF}\u{1F1F4}",r:"middleeast",n:"Amazon (cross-border)",url:"amazon.com",t:"retail",traffic:"~3M/mo (JO)",fee:"Ship qu\u1ed1c t\u1ebf",feat:"Global Store, USD"},
{g:"Africa & ME",c:"Jordan",f:"\u{1F1EF}\u{1F1F4}",r:"middleeast",n:"OLX Jordan",url:"olx.jo",t:"classified",traffic:"~2M/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"Mua b\u00e1n C2C"},
{g:"Africa & ME",c:"Jordan",f:"\u{1F1EF}\u{1F1F4}",r:"middleeast",n:"Marka VIP",url:"markavip.com",t:"fashion",traffic:"~1M/mo",fee:"Flash sales",feat:"Th\u1eddi trang gi\u1ea3m gi\u00e1, brands"},
{g:"Africa & ME",c:"Jordan",f:"\u{1F1EF}\u{1F1F4}",r:"middleeast",n:"Carrefour JO",url:"carrefourjordan.com",t:"retail",traffic:"~800K/mo",fee:"Retail",feat:"Grocery & \u0111i\u1ec7n t\u1eed"},
{g:"Africa & ME",c:"Jordan",f:"\u{1F1EF}\u{1F1F4}",r:"middleeast",n:"Jamalon",url:"jamalon.com",t:"retail",traffic:"~600K/mo",fee:"Retail",feat:"S\u00e1ch ti\u1ebfng \u1ea2 R\u1eadp & Anh"},
{g:"Africa & ME",c:"Jordan",f:"\u{1F1EF}\u{1F1F4}",r:"middleeast",n:"Ubuy JO",url:"ubuy.jo",t:"marketplace",traffic:"~400K/mo",fee:"Cross-border",feat:"Nh\u1eadp kh\u1ea9u qu\u1ed1c t\u1ebf"},
{g:"Africa & ME",c:"Jordan",f:"\u{1F1EF}\u{1F1F4}",r:"middleeast",n:"Talabat JO",url:"talabat.com/jordan",t:"retail",traffic:"~2M/mo",fee:"Delivery",feat:"Food & grocery delivery"},
{g:"Africa & ME",c:"Jordan",f:"\u{1F1EF}\u{1F1F4}",r:"middleeast",n:"Snobb",url:"snobb.com",t:"fashion",traffic:"~200K/mo",fee:"Retail",feat:"Sneakers & streetwear"},
{g:"Africa & ME",c:"Jordan",f:"\u{1F1EF}\u{1F1F4}",r:"middleeast",n:"Smartbuy JO",url:"smartbuy.jo",t:"electronics",traffic:"~300K/mo",fee:"Retail",feat:"\u0110i\u1ec7n t\u1eed, smartphone"},
{g:"Africa & ME",c:"Lebanon",f:"\u{1F1F1}\u{1F1E7}",r:"middleeast",n:"OLX Lebanon",url:"olx.com.lb",t:"classified",traffic:"~3M/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"Classified #1 Lebanon, C2C"},
{g:"Africa & ME",c:"Lebanon",f:"\u{1F1F1}\u{1F1E7}",r:"middleeast",n:"Opensooq LB",url:"opensooq.com/lb",t:"classified",traffic:"~1.5M/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"Rao v\u1eb7t \u0111a danh m\u1ee5c"},
{g:"Africa & ME",c:"Lebanon",f:"\u{1F1F1}\u{1F1E7}",r:"middleeast",n:"Amazon (cross-border)",url:"amazon.com",t:"retail",traffic:"~2M/mo (LB)",fee:"Ship qu\u1ed1c t\u1ebf",feat:"Global, thanh to\u00e1n USD"},
{g:"Africa & ME",c:"Lebanon",f:"\u{1F1F1}\u{1F1E7}",r:"middleeast",n:"AliExpress LB",url:"aliexpress.com",t:"marketplace",traffic:"~2.5M/mo (LB)",fee:"Cross-border",feat:"Gi\u00e1 r\u1ebb, ship t\u1eeb TQ"},
{g:"Africa & ME",c:"Lebanon",f:"\u{1F1F1}\u{1F1E7}",r:"middleeast",n:"Shein LB",url:"shein.com",t:"fashion",traffic:"~1.5M/mo (LB)",fee:"Cross-border",feat:"Fast fashion gi\u00e1 r\u1ebb"},
{g:"Africa & ME",c:"Lebanon",f:"\u{1F1F1}\u{1F1E7}",r:"middleeast",n:"Keeward",url:"keeward.com",t:"marketplace",traffic:"~300K/mo",fee:"Local marketplace",feat:"N\u1ec1n t\u1ea3ng local"},
{g:"Africa & ME",c:"Lebanon",f:"\u{1F1F1}\u{1F1E7}",r:"middleeast",n:"Lebtivity",url:"lebtivity.com",t:"marketplace",traffic:"~200K/mo",fee:"Free listing",feat:"Events & services"},
{g:"Africa & ME",c:"Lebanon",f:"\u{1F1F1}\u{1F1E7}",r:"middleeast",n:"Dajin LB",url:"dajin.com.lb",t:"electronics",traffic:"~150K/mo",fee:"Retail",feat:"\u0110i\u1ec7n t\u1eed \u0111\u1ecba ph\u01b0\u01a1ng"},
{g:"Africa & ME",c:"Lebanon",f:"\u{1F1F1}\u{1F1E7}",r:"middleeast",n:"Temu LB",url:"temu.com",t:"marketplace",traffic:"~1M/mo (LB)",fee:"Cross-border",feat:"Ultra gi\u00e1 r\u1ebb, ship tr\u1ef1c ti\u1ebfp"},
{g:"Africa & ME",c:"Lebanon",f:"\u{1F1F1}\u{1F1E7}",r:"middleeast",n:"Spinneys LB",url:"spinneys.com",t:"retail",traffic:"~400K/mo",fee:"Retail",feat:"Grocery cao c\u1ea5p"},
{g:"Africa & ME",c:"Iraq",f:"\u{1F1EE}\u{1F1F6}",r:"middleeast",n:"Opensooq IQ",url:"opensooq.com/iq",t:"classified",traffic:"~5M/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"Classified l\u1edbn nh\u1ea5t Iraq"},
{g:"Africa & ME",c:"Iraq",f:"\u{1F1EE}\u{1F1F6}",r:"middleeast",n:"Amazon (cross-border)",url:"amazon.com",t:"retail",traffic:"~2M/mo (IQ)",fee:"Ship qu\u1ed1c t\u1ebf",feat:"Global Store, ship ch\u1eadm"},
{g:"Africa & ME",c:"Iraq",f:"\u{1F1EE}\u{1F1F6}",r:"middleeast",n:"AliExpress IQ",url:"aliexpress.com",t:"marketplace",traffic:"~4M/mo (IQ)",fee:"Cross-border",feat:"Ph\u1ed5 bi\u1ebfn nh\u1ea5t, gi\u00e1 r\u1ebb"},
{g:"Africa & ME",c:"Iraq",f:"\u{1F1EE}\u{1F1F6}",r:"middleeast",n:"Miswag",url:"miswag.com",t:"marketplace",traffic:"~1.5M/mo",fee:"COD based",feat:"Marketplace local Iraq, COD 100%"},
{g:"Africa & ME",c:"Iraq",f:"\u{1F1EE}\u{1F1F6}",r:"middleeast",n:"Orisdi",url:"orisdi.com",t:"marketplace",traffic:"~800K/mo",fee:"Marketplace",feat:"TMDT Iraq, nhi\u1ec1u danh m\u1ee5c"},
{g:"Africa & ME",c:"Iraq",f:"\u{1F1EE}\u{1F1F6}",r:"middleeast",n:"Shopini",url:"shopini.com",t:"retail",traffic:"~400K/mo",fee:"Forwarding",feat:"Ship forwarding t\u1eeb US/UK"},
{g:"Africa & ME",c:"Iraq",f:"\u{1F1EE}\u{1F1F6}",r:"middleeast",n:"Shein IQ",url:"shein.com",t:"fashion",traffic:"~2M/mo (IQ)",fee:"Cross-border",feat:"Fast fashion"},
{g:"Africa & ME",c:"Iraq",f:"\u{1F1EE}\u{1F1F6}",r:"middleeast",n:"Temu IQ",url:"temu.com",t:"marketplace",traffic:"~1M/mo (IQ)",fee:"Cross-border",feat:"Gi\u00e1 si\u00eau r\u1ebb"},
{g:"Africa & ME",c:"Iraq",f:"\u{1F1EE}\u{1F1F6}",r:"middleeast",n:"Lezzoo",url:"lezzoo.com",t:"retail",traffic:"~500K/mo",fee:"Delivery",feat:"Super app Iraq"},
{g:"Africa & ME",c:"Iraq",f:"\u{1F1EE}\u{1F1F6}",r:"middleeast",n:"1001Shops IQ",url:"1001shops.com",t:"marketplace",traffic:"~200K/mo",fee:"Commission",feat:"Marketplace \u0111\u1ecba ph\u01b0\u01a1ng"},
{g:"Africa & ME",c:"Iran",f:"\u{1F1EE}\u{1F1F7}",r:"middleeast",n:"Digikala",url:"digikala.com",t:"marketplace",traffic:"~120M/mo",fee:"8-15% hoa h\u1ed3ng",feat:"Amazon c\u1ee7a Iran, \u0111i\u1ec7n t\u1eed, t\u1ea5t c\u1ea3"},
{g:"Africa & ME",c:"Iran",f:"\u{1F1EE}\u{1F1F7}",r:"middleeast",n:"Divar",url:"divar.ir",t:"classified",traffic:"~90M/mo",fee:"Mi\u1ec5n ph\u00ed + boost",feat:"Classified #1 Iran, nh\u01b0 Kleinanzeigen!"},
{g:"Africa & ME",c:"Iran",f:"\u{1F1EE}\u{1F1F7}",r:"middleeast",n:"Sheypoor",url:"sheypoor.com",t:"classified",traffic:"~30M/mo",fee:"Mi\u1ec5n ph\u00ed + premium",feat:"Classified #2, xe, BDS, \u0111\u1ed3 c\u0169"},
{g:"Africa & ME",c:"Iran",f:"\u{1F1EE}\u{1F1F7}",r:"middleeast",n:"Basalam",url:"basalam.com",t:"marketplace",traffic:"~15M/mo",fee:"5-12% hoa h\u1ed3ng",feat:"Marketplace social, handmade, SME"},
{g:"Africa & ME",c:"Iran",f:"\u{1F1EE}\u{1F1F7}",r:"middleeast",n:"Torob",url:"torob.com",t:"marketplace",traffic:"~25M/mo",fee:"CPC",feat:"So s\u00e1nh gi\u00e1, search engine mua s\u1eafm"},
{g:"Africa & ME",c:"Iran",f:"\u{1F1EE}\u{1F1F7}",r:"middleeast",n:"Snapp Market",url:"snapp.market",t:"retail",traffic:"~10M/mo",fee:"Delivery",feat:"Grocery delivery, super app"},
{g:"Africa & ME",c:"Iran",f:"\u{1F1EE}\u{1F1F7}",r:"middleeast",n:"Bamilo",url:"bamilo.com",t:"marketplace",traffic:"~5M/mo",fee:"Commission",feat:"Marketplace t\u1ed5ng h\u1ee3p"},
{g:"Africa & ME",c:"Iran",f:"\u{1F1EE}\u{1F1F7}",r:"middleeast",n:"Takhfifan",url:"takhfifan.com",t:"marketplace",traffic:"~8M/mo",fee:"Revenue share",feat:"Deal & coupon, group buying"},
{g:"Africa & ME",c:"Iran",f:"\u{1F1EE}\u{1F1F7}",r:"middleeast",n:"Alibaba.ir",url:"alibaba.ir",t:"retail",traffic:"~12M/mo",fee:"Service fee",feat:"V\u00e9 m\u00e1y bay, du l\u1ecbch (kh\u00e1c Alibaba.com)"},
{g:"Africa & ME",c:"Iran",f:"\u{1F1EE}\u{1F1F7}",r:"middleeast",n:"MoboDB",url:"mobodb.com",t:"electronics",traffic:"~3M/mo",fee:"CPC/listing",feat:"So s\u00e1nh \u0111i\u1ec7n tho\u1ea1i, gi\u00e1 t\u1ed1t"},
{g:"Africa & ME",c:"Egypt",f:"\u{1F1EA}\u{1F1EC}",r:"northafrica",n:"Amazon.eg (Souq)",url:"amazon.eg",t:"retail",traffic:"~50M/mo",fee:"5-15% hoa h\u1ed3ng",feat:"FBA, Prime Egypt, COD"},
{g:"Africa & ME",c:"Egypt",f:"\u{1F1EA}\u{1F1EC}",r:"northafrica",n:"Noon Egypt",url:"noon.com/egypt",t:"marketplace",traffic:"~20M/mo",fee:"5-20% hoa h\u1ed3ng",feat:"Noon Express, NoonPay"},
{g:"Africa & ME",c:"Egypt",f:"\u{1F1EA}\u{1F1EC}",r:"northafrica",n:"OLX Egypt",url:"olx.com.eg",t:"classified",traffic:"~25M/mo",fee:"Mi\u1ec5n ph\u00ed + boost",feat:"Classified #1 Egypt, C2C \u0111\u1ed3 c\u0169"},
{g:"Africa & ME",c:"Egypt",f:"\u{1F1EA}\u{1F1EC}",r:"northafrica",n:"Jumia Egypt",url:"jumia.com.eg",t:"marketplace",traffic:"~15M/mo",fee:"5-20% hoa h\u1ed3ng",feat:"Marketplace l\u1edbn, COD, J-Force"},
{g:"Africa & ME",c:"Egypt",f:"\u{1F1EA}\u{1F1EC}",r:"northafrica",n:"Dubizzle Egypt",url:"dubizzle.com.eg",t:"classified",traffic:"~8M/mo",fee:"Mi\u1ec5n ph\u00ed + premium",feat:"BDS, xe, vi\u1ec7c l\u00e0m"},
{g:"Africa & ME",c:"Egypt",f:"\u{1F1EA}\u{1F1EC}",r:"northafrica",n:"B.Tech",url:"btech.com",t:"electronics",traffic:"~6M/mo",fee:"Retail",feat:"\u0110i\u1ec7n t\u1eed, gia d\u1ee5ng, tr\u1ea3 g\u00f3p"},
{g:"Africa & ME",c:"Egypt",f:"\u{1F1EA}\u{1F1EC}",r:"northafrica",n:"2B Egypt",url:"2b.com.eg",t:"electronics",traffic:"~3M/mo",fee:"Retail",feat:"\u0110i\u1ec7n t\u1eed, smartphone"},
{g:"Africa & ME",c:"Egypt",f:"\u{1F1EA}\u{1F1EC}",r:"northafrica",n:"Talabat EG",url:"talabat.com/egypt",t:"retail",traffic:"~5M/mo",fee:"Delivery",feat:"Food & grocery delivery"},
{g:"Africa & ME",c:"Egypt",f:"\u{1F1EA}\u{1F1EC}",r:"northafrica",n:"Breadfast",url:"breadfast.com",t:"retail",traffic:"~2M/mo",fee:"Retail/delivery",feat:"Grocery giao s\u00e1ng s\u1edbm"},
{g:"Africa & ME",c:"Egypt",f:"\u{1F1EA}\u{1F1EC}",r:"northafrica",n:"Homzmart",url:"homzmart.com",t:"retail",traffic:"~1.5M/mo",fee:"Marketplace",feat:"N\u1ed9i th\u1ea5t & gia d\u1ee5ng online"},
{g:"Africa & ME",c:"Morocco",f:"\u{1F1F2}\u{1F1E6}",r:"northafrica",n:"Jumia Morocco",url:"jumia.ma",t:"marketplace",traffic:"~12M/mo",fee:"5-20% hoa h\u1ed3ng",feat:"Marketplace #1 Morocco, COD"},
{g:"Africa & ME",c:"Morocco",f:"\u{1F1F2}\u{1F1E6}",r:"northafrica",n:"Avito.ma",url:"avito.ma",t:"classified",traffic:"~18M/mo",fee:"Mi\u1ec5n ph\u00ed + boost",feat:"Classified #1 Morocco, nh\u01b0 Kleinanzeigen!"},
{g:"Africa & ME",c:"Morocco",f:"\u{1F1F2}\u{1F1E6}",r:"northafrica",n:"Hmizate",url:"hmizate.ma",t:"marketplace",traffic:"~2M/mo",fee:"Deal/voucher",feat:"Flash deals, coupon"},
{g:"Africa & ME",c:"Morocco",f:"\u{1F1F2}\u{1F1E6}",r:"northafrica",n:"Marjane.ma",url:"marjane.ma",t:"retail",traffic:"~1.5M/mo",fee:"Retail",feat:"Hypermarket online"},
{g:"Africa & ME",c:"Morocco",f:"\u{1F1F2}\u{1F1E6}",r:"northafrica",n:"Electroplanet",url:"electroplanet.ma",t:"electronics",traffic:"~1M/mo",fee:"Retail",feat:"\u0110i\u1ec7n t\u1eed, gia d\u1ee5ng"},
{g:"Africa & ME",c:"Morocco",f:"\u{1F1F2}\u{1F1E6}",r:"northafrica",n:"Cosmos Electro",url:"cosmos.ma",t:"electronics",traffic:"~800K/mo",fee:"Retail",feat:"\u0110i\u1ec7n m\u00e1y"},
{g:"Africa & ME",c:"Morocco",f:"\u{1F1F2}\u{1F1E6}",r:"northafrica",n:"Glovo MA",url:"glovoapp.com/ma",t:"retail",traffic:"~2M/mo",fee:"Delivery",feat:"Delivery \u0111a d\u1ecbch v\u1ee5"},
{g:"Africa & ME",c:"Morocco",f:"\u{1F1F2}\u{1F1E6}",r:"northafrica",n:"AliExpress MA",url:"aliexpress.com",t:"marketplace",traffic:"~5M/mo (MA)",fee:"Cross-border",feat:"Gi\u00e1 r\u1ebb ship TQ"},
{g:"Africa & ME",c:"Morocco",f:"\u{1F1F2}\u{1F1E6}",r:"northafrica",n:"Selecto.ma",url:"selecto.ma",t:"marketplace",traffic:"~500K/mo",fee:"Marketplace",feat:"Local marketplace"},
{g:"Africa & ME",c:"Morocco",f:"\u{1F1F2}\u{1F1E6}",r:"northafrica",n:"Souk.ma",url:"souk.ma",t:"classified",traffic:"~400K/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"Rao v\u1eb7t \u0111\u1ecba ph\u01b0\u01a1ng"},
{g:"Africa & ME",c:"Tunisia",f:"\u{1F1F9}\u{1F1F3}",r:"northafrica",n:"Jumia Tunisia",url:"jumia.com.tn",t:"marketplace",traffic:"~3M/mo",fee:"5-20%",feat:"Marketplace, COD"},
{g:"Africa & ME",c:"Tunisia",f:"\u{1F1F9}\u{1F1F3}",r:"northafrica",n:"Tayara.tn",url:"tayara.tn",t:"classified",traffic:"~8M/mo",fee:"Mi\u1ec5n ph\u00ed + boost",feat:"Classified #1 Tunisia, \u0111\u1ed3 c\u0169, xe, BDS"},
{g:"Africa & ME",c:"Tunisia",f:"\u{1F1F9}\u{1F1F3}",r:"northafrica",n:"Mytek.tn",url:"mytek.tn",t:"electronics",traffic:"~2M/mo",fee:"Retail",feat:"\u0110i\u1ec7n t\u1eed #1 Tunisia"},
{g:"Africa & ME",c:"Tunisia",f:"\u{1F1F9}\u{1F1F3}",r:"northafrica",n:"Tunisianet",url:"tunisianet.com.tn",t:"electronics",traffic:"~1.5M/mo",fee:"Retail",feat:"\u0110i\u1ec7n t\u1eed, IT, gaming"},
{g:"Africa & ME",c:"Tunisia",f:"\u{1F1F9}\u{1F1F3}",r:"northafrica",n:"SfaxInfo",url:"sfaxinfo.com",t:"classified",traffic:"~500K/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"Classified regional"},
{g:"Africa & ME",c:"Tunisia",f:"\u{1F1F9}\u{1F1F3}",r:"northafrica",n:"Zoom.tn",url:"zoom.tn",t:"marketplace",traffic:"~400K/mo",fee:"CPC",feat:"So s\u00e1nh gi\u00e1"},
{g:"Africa & ME",c:"Tunisia",f:"\u{1F1F9}\u{1F1F3}",r:"northafrica",n:"AliExpress TN",url:"aliexpress.com",t:"marketplace",traffic:"~3M/mo (TN)",fee:"Cross-border",feat:"Ph\u1ed5 bi\u1ebfn, gi\u00e1 r\u1ebb"},
{g:"Africa & ME",c:"Tunisia",f:"\u{1F1F9}\u{1F1F3}",r:"northafrica",n:"Carrefour TN",url:"carrefour.tn",t:"retail",traffic:"~600K/mo",fee:"Retail",feat:"Grocery & gia d\u1ee5ng"},
{g:"Africa & ME",c:"Tunisia",f:"\u{1F1F9}\u{1F1F3}",r:"northafrica",n:"Shein TN",url:"shein.com",t:"fashion",traffic:"~2M/mo (TN)",fee:"Cross-border",feat:"Fast fashion"},
{g:"Africa & ME",c:"Tunisia",f:"\u{1F1F9}\u{1F1F3}",r:"northafrica",n:"Afariat.com",url:"afariat.com",t:"classified",traffic:"~300K/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"Rao v\u1eb7t Tunisia"},
{g:"Africa & ME",c:"Algeria",f:"\u{1F1E9}\u{1F1FF}",r:"northafrica",n:"Ouedkniss",url:"ouedkniss.com",t:"classified",traffic:"~35M/mo",fee:"Mi\u1ec5n ph\u00ed + boost",feat:"Classified #1 Algeria, nh\u01b0 Kleinanzeigen!"},
{g:"Africa & ME",c:"Algeria",f:"\u{1F1E9}\u{1F1FF}",r:"northafrica",n:"Jumia Algeria",url:"jumia.dz",t:"marketplace",traffic:"~5M/mo",fee:"5-20%",feat:"Marketplace, COD, J-Force"},
{g:"Africa & ME",c:"Algeria",f:"\u{1F1E9}\u{1F1FF}",r:"northafrica",n:"Echrily.com",url:"echrily.com",t:"marketplace",traffic:"~1M/mo",fee:"Commission",feat:"Marketplace \u0111\u1ecba ph\u01b0\u01a1ng"},
{g:"Africa & ME",c:"Algeria",f:"\u{1F1E9}\u{1F1FF}",r:"northafrica",n:"Batolis",url:"batolis.com",t:"marketplace",traffic:"~500K/mo",fee:"Commission",feat:"TMDT Algeria"},
{g:"Africa & ME",c:"Algeria",f:"\u{1F1E9}\u{1F1FF}",r:"northafrica",n:"AliExpress DZ",url:"aliexpress.com",t:"marketplace",traffic:"~8M/mo (DZ)",fee:"Cross-border",feat:"R\u1ea5t ph\u1ed5 bi\u1ebfn t\u1ea1i Algeria"},
{g:"Africa & ME",c:"Algeria",f:"\u{1F1E9}\u{1F1FF}",r:"northafrica",n:"Shein DZ",url:"shein.com",t:"fashion",traffic:"~3M/mo (DZ)",fee:"Cross-border",feat:"Fast fashion"},
{g:"Africa & ME",c:"Algeria",f:"\u{1F1E9}\u{1F1FF}",r:"northafrica",n:"Hmizate DZ",url:"hmizate.dz",t:"marketplace",traffic:"~300K/mo",fee:"Deals",feat:"Daily deals"},
{g:"Africa & ME",c:"Algeria",f:"\u{1F1E9}\u{1F1FF}",r:"northafrica",n:"Emploitic",url:"emploitic.com",t:"classified",traffic:"~2M/mo",fee:"Vi\u1ec7c l\u00e0m",feat:"Vi\u1ec7c l\u00e0m + d\u1ecbch v\u1ee5"},
{g:"Africa & ME",c:"Algeria",f:"\u{1F1E9}\u{1F1FF}",r:"northafrica",n:"Maystro Livraison",url:"maystro.com",t:"marketplace",traffic:"~200K/mo",fee:"Delivery",feat:"Logistics TMDT"},
{g:"Africa & ME",c:"Algeria",f:"\u{1F1E9}\u{1F1FF}",r:"northafrica",n:"Yassir",url:"yassir.com",t:"retail",traffic:"~1M/mo",fee:"Delivery",feat:"Super app: taxi, food, grocery"},
{g:"Africa & ME",c:"Nigeria",f:"\u{1F1F3}\u{1F1EC}",r:"westafrica",n:"Jumia Nigeria",url:"jumia.com.ng",t:"marketplace",traffic:"~30M/mo",fee:"5-20% hoa h\u1ed3ng",feat:"Marketplace #1 Nigeria, COD, J-Force"},
{g:"Africa & ME",c:"Nigeria",f:"\u{1F1F3}\u{1F1EC}",r:"westafrica",n:"Jiji.ng",url:"jiji.ng",t:"classified",traffic:"~20M/mo",fee:"Mi\u1ec5n ph\u00ed + boost",feat:"Classified #1 Nigeria, \u0111\u1ed3 c\u0169, xe, \u0111i\u1ec7n tho\u1ea1i"},
{g:"Africa & ME",c:"Nigeria",f:"\u{1F1F3}\u{1F1EC}",r:"westafrica",n:"Konga",url:"konga.com",t:"marketplace",traffic:"~8M/mo",fee:"5-15%",feat:"Marketplace, KongaPay, \u0111i\u1ec7n t\u1eed"},
{g:"Africa & ME",c:"Nigeria",f:"\u{1F1F3}\u{1F1EC}",r:"westafrica",n:"OLX Nigeria",url:"olx.com.ng",t:"classified",traffic:"~3M/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"Classified C2C"},
{g:"Africa & ME",c:"Nigeria",f:"\u{1F1F3}\u{1F1EC}",r:"westafrica",n:"Payporte",url:"payporte.com",t:"fashion",traffic:"~1.5M/mo",fee:"Retail",feat:"Th\u1eddi trang Nigeria, affordable"},
{g:"Africa & ME",c:"Nigeria",f:"\u{1F1F3}\u{1F1EC}",r:"westafrica",n:"Kara.com.ng",url:"kara.com.ng",t:"electronics",traffic:"~2M/mo",fee:"Retail",feat:"\u0110i\u1ec7n t\u1eed, gia d\u1ee5ng"},
{g:"Africa & ME",c:"Nigeria",f:"\u{1F1F3}\u{1F1EC}",r:"westafrica",n:"Slot.ng",url:"slot.ng",t:"electronics",traffic:"~3M/mo",fee:"Retail",feat:"Smartphone, ph\u1ee5 ki\u1ec7n"},
{g:"Africa & ME",c:"Nigeria",f:"\u{1F1F3}\u{1F1EC}",r:"westafrica",n:"Olist",url:"olist.ng",t:"marketplace",traffic:"~1M/mo",fee:"Commission",feat:"B2B2C marketplace"},
{g:"Africa & ME",c:"Nigeria",f:"\u{1F1F3}\u{1F1EC}",r:"westafrica",n:"Supermart.ng",url:"supermart.ng",t:"retail",traffic:"~500K/mo",fee:"Retail",feat:"Grocery online Lagos"},
{g:"Africa & ME",c:"Nigeria",f:"\u{1F1F3}\u{1F1EC}",r:"westafrica",n:"Flutterwave Store",url:"flutterwave.com/store",t:"marketplace",traffic:"~2M/mo",fee:"Payment platform",feat:"Thanh to\u00e1n & store builder"},
{g:"Africa & ME",c:"South Africa",f:"\u{1F1FF}\u{1F1E6}",r:"southernafrica",n:"Takealot",url:"takealot.com",t:"marketplace",traffic:"~25M/mo",fee:"7-15% hoa h\u1ed3ng",feat:"Amazon c\u1ee7a ZA, Takealot Delivery"},
{g:"Africa & ME",c:"South Africa",f:"\u{1F1FF}\u{1F1E6}",r:"southernafrica",n:"Gumtree ZA",url:"gumtree.co.za",t:"classified",traffic:"~15M/mo",fee:"Mi\u1ec5n ph\u00ed + boost",feat:"Classified #1 ZA, nh\u01b0 Kleinanzeigen!"},
{g:"Africa & ME",c:"South Africa",f:"\u{1F1FF}\u{1F1E6}",r:"southernafrica",n:"OLX South Africa",url:"olx.co.za",t:"classified",traffic:"~8M/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"C2C, xe, \u0111\u1ed3 c\u0169"},
{g:"Africa & ME",c:"South Africa",f:"\u{1F1FF}\u{1F1E6}",r:"southernafrica",n:"Bidorbuy",url:"bidorbuy.co.za",t:"marketplace",traffic:"~5M/mo",fee:"5-10% hoa h\u1ed3ng",feat:"\u0110\u1ea5u gi\u00e1 + fixed price, C2C/B2C"},
{g:"Africa & ME",c:"South Africa",f:"\u{1F1FF}\u{1F1E6}",r:"southernafrica",n:"Superbalist",url:"superbalist.com",t:"fashion",traffic:"~4M/mo",fee:"Retail/marketplace",feat:"Th\u1eddi trang, lifestyle, tr\u1ebb"},
{g:"Africa & ME",c:"South Africa",f:"\u{1F1FF}\u{1F1E6}",r:"southernafrica",n:"Makro",url:"makro.co.za",t:"retail",traffic:"~6M/mo",fee:"Retail",feat:"Wholesale & retail, \u0111i\u1ec7n t\u1eed"},
{g:"Africa & ME",c:"South Africa",f:"\u{1F1FF}\u{1F1E6}",r:"southernafrica",n:"Loot.co.za",url:"loot.co.za",t:"retail",traffic:"~2M/mo",fee:"Retail",feat:"S\u00e1ch, \u0111i\u1ec7n t\u1eed, gaming"},
{g:"Africa & ME",c:"South Africa",f:"\u{1F1FF}\u{1F1E6}",r:"southernafrica",n:"Cash Converters ZA",url:"cashconverters.co.za",t:"secondhand",traffic:"~1.5M/mo",fee:"Mua l\u1ea1i 40-60%",feat:"Secondhand ch\u00ednh h\u00e3ng, c\u1ea7m \u0111\u1ed3"},
{g:"Africa & ME",c:"South Africa",f:"\u{1F1FF}\u{1F1E6}",r:"southernafrica",n:"Zando",url:"zando.co.za",t:"fashion",traffic:"~3M/mo",fee:"Retail",feat:"Th\u1eddi trang & gi\u00e0y, free return"},
{g:"Africa & ME",c:"South Africa",f:"\u{1F1FF}\u{1F1E6}",r:"southernafrica",n:"Bob Shop",url:"bobshop.co.za",t:"marketplace",traffic:"~2M/mo",fee:"Marketplace",feat:"\u0110i\u1ec7n t\u1eed, gia d\u1ee5ng, gi\u00e1 t\u1ed1t"},
{g:"Africa & ME",c:"Kenya",f:"\u{1F1F0}\u{1F1EA}",r:"eastafrica",n:"Jumia Kenya",url:"jumia.co.ke",t:"marketplace",traffic:"~10M/mo",fee:"5-20%",feat:"Marketplace #1 Kenya, M-Pesa"},
{g:"Africa & ME",c:"Kenya",f:"\u{1F1F0}\u{1F1EA}",r:"eastafrica",n:"Jiji.co.ke",url:"jiji.co.ke",t:"classified",traffic:"~6M/mo",fee:"Mi\u1ec5n ph\u00ed + boost",feat:"Classified #1 Kenya, \u0111\u1ed3 c\u0169, xe"},
{g:"Africa & ME",c:"Kenya",f:"\u{1F1F0}\u{1F1EA}",r:"eastafrica",n:"OLX Kenya",url:"olx.co.ke",t:"classified",traffic:"~3M/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"C2C marketplace"},
{g:"Africa & ME",c:"Kenya",f:"\u{1F1F0}\u{1F1EA}",r:"eastafrica",n:"Kilimall",url:"kilimall.co.ke",t:"marketplace",traffic:"~4M/mo",fee:"5-15%",feat:"Marketplace, cross-border TQ"},
{g:"Africa & ME",c:"Kenya",f:"\u{1F1F0}\u{1F1EA}",r:"eastafrica",n:"Masoko",url:"masoko.com",t:"marketplace",traffic:"~1.5M/mo",fee:"Commission",feat:"Safaricom marketplace, M-Pesa"},
{g:"Africa & ME",c:"Kenya",f:"\u{1F1F0}\u{1F1EA}",r:"eastafrica",n:"PigiaMe",url:"pigiame.co.ke",t:"classified",traffic:"~2M/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"Classified \u0111\u1ecba ph\u01b0\u01a1ng"},
{g:"Africa & ME",c:"Kenya",f:"\u{1F1F0}\u{1F1EA}",r:"eastafrica",n:"Zuricart",url:"zuricart.co.ke",t:"marketplace",traffic:"~500K/mo",fee:"Commission",feat:"Marketplace Kenya"},
{g:"Africa & ME",c:"Kenya",f:"\u{1F1F0}\u{1F1EA}",r:"eastafrica",n:"Naivas Online",url:"naivas.online",t:"retail",traffic:"~800K/mo",fee:"Retail",feat:"Grocery chain online"},
{g:"Africa & ME",c:"Kenya",f:"\u{1F1F0}\u{1F1EA}",r:"eastafrica",n:"Glovo KE",url:"glovoapp.com/ke",t:"retail",traffic:"~1.5M/mo",fee:"Delivery",feat:"Multi-delivery app"},
{g:"Africa & ME",c:"Kenya",f:"\u{1F1F0}\u{1F1EA}",r:"eastafrica",n:"Sky.Garden",url:"sky.garden",t:"marketplace",traffic:"~400K/mo",fee:"Commission",feat:"Marketplace \u0111\u1ecba ph\u01b0\u01a1ng"},
{g:"Africa & ME",c:"Ghana",f:"\u{1F1EC}\u{1F1ED}",r:"westafrica",n:"Jumia Ghana",url:"jumia.com.gh",t:"marketplace",traffic:"~5M/mo",fee:"5-20%",feat:"Marketplace #1 Ghana, COD"},
{g:"Africa & ME",c:"Ghana",f:"\u{1F1EC}\u{1F1ED}",r:"westafrica",n:"Jiji Ghana",url:"jiji.com.gh",t:"classified",traffic:"~4M/mo",fee:"Mi\u1ec5n ph\u00ed + boost",feat:"Classified #1 Ghana, C2C"},
{g:"Africa & ME",c:"Ghana",f:"\u{1F1EC}\u{1F1ED}",r:"westafrica",n:"OLX Ghana",url:"olx.com.gh",t:"classified",traffic:"~1.5M/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"Mua b\u00e1n C2C"},
{g:"Africa & ME",c:"Ghana",f:"\u{1F1EC}\u{1F1ED}",r:"westafrica",n:"Tonaton",url:"tonaton.com",t:"classified",traffic:"~2M/mo",fee:"Mi\u1ec5n ph\u00ed + premium",feat:"Classified Ghana, \u0111\u1ed3 c\u0169"},
{g:"Africa & ME",c:"Ghana",f:"\u{1F1EC}\u{1F1ED}",r:"westafrica",n:"Melcom Online",url:"melcomonline.com",t:"retail",traffic:"~500K/mo",fee:"Retail",feat:"Department store online"},
{g:"Africa & ME",c:"Ghana",f:"\u{1F1EC}\u{1F1ED}",r:"westafrica",n:"CompuGhana",url:"compughana.com",t:"electronics",traffic:"~600K/mo",fee:"Retail",feat:"\u0110i\u1ec7n t\u1eed, laptop, smartphone"},
{g:"Africa & ME",c:"Ghana",f:"\u{1F1EC}\u{1F1ED}",r:"westafrica",n:"Kikuu Ghana",url:"kikuu.com",t:"marketplace",traffic:"~800K/mo",fee:"Cross-border",feat:"Ship t\u1eeb TQ gi\u00e1 r\u1ebb"},
{g:"Africa & ME",c:"Ghana",f:"\u{1F1EC}\u{1F1ED}",r:"westafrica",n:"Zoobashop",url:"zoobashop.com",t:"electronics",traffic:"~400K/mo",fee:"Retail",feat:"Smartphone & accessories"},
{g:"Africa & ME",c:"Ghana",f:"\u{1F1EC}\u{1F1ED}",r:"westafrica",n:"Hubtel Market",url:"hubtel.com",t:"marketplace",traffic:"~1M/mo",fee:"Commission",feat:"Super app: pay, shop, delivery"},
{g:"Africa & ME",c:"Ghana",f:"\u{1F1EC}\u{1F1ED}",r:"westafrica",n:"Reapp Ghana",url:"reapp.com",t:"secondhand",traffic:"~200K/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"Secondhand \u0111i\u1ec7n tho\u1ea1i"},
{g:"Africa & ME",c:"Tanzania",f:"\u{1F1F9}\u{1F1FF}",r:"eastafrica",n:"Jumia Tanzania",url:"jumia.co.tz",t:"marketplace",traffic:"~3M/mo",fee:"5-20%",feat:"Marketplace #1 TZ"},
{g:"Africa & ME",c:"Tanzania",f:"\u{1F1F9}\u{1F1FF}",r:"eastafrica",n:"Jiji Tanzania",url:"jiji.co.tz",t:"classified",traffic:"~2M/mo",fee:"Mi\u1ec5n ph\u00ed + boost",feat:"Classified #1 TZ, C2C"},
{g:"Africa & ME",c:"Tanzania",f:"\u{1F1F9}\u{1F1FF}",r:"eastafrica",n:"ZoomTanzania",url:"zoomtanzania.com",t:"classified",traffic:"~800K/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"Rao v\u1eb7t local"},
{g:"Africa & ME",c:"Tanzania",f:"\u{1F1F9}\u{1F1FF}",r:"eastafrica",n:"DukaPress",url:"dukapress.com",t:"marketplace",traffic:"~200K/mo",fee:"SaaS",feat:"N\u1ec1n t\u1ea3ng b\u00e1n h\u00e0ng"},
{g:"Africa & ME",c:"Tanzania",f:"\u{1F1F9}\u{1F1FF}",r:"eastafrica",n:"Kivuko",url:"kivuko.co.tz",t:"marketplace",traffic:"~150K/mo",fee:"Commission",feat:"Marketplace TZ"},
{g:"Africa & ME",c:"Tanzania",f:"\u{1F1F9}\u{1F1FF}",r:"eastafrica",n:"Kupatana",url:"kupatana.com",t:"classified",traffic:"~600K/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"Classified C2C Tanzania"},
{g:"Africa & ME",c:"Tanzania",f:"\u{1F1F9}\u{1F1FF}",r:"eastafrica",n:"Mwananchi Mall",url:"mall.mwananchi.co.tz",t:"marketplace",traffic:"~100K/mo",fee:"Commission",feat:"Media-backed marketplace"},
{g:"Africa & ME",c:"Tanzania",f:"\u{1F1F9}\u{1F1FF}",r:"eastafrica",n:"BuyRent Kenya (TZ)",url:"buyrentkenya.com",t:"classified",traffic:"~300K/mo (TZ)",fee:"Premium listing",feat:"B\u0110S & cho thu\u00ea"},
{g:"Africa & ME",c:"Tanzania",f:"\u{1F1F9}\u{1F1FF}",r:"eastafrica",n:"Vodacom Shop TZ",url:"vodacom.co.tz",t:"electronics",traffic:"~500K/mo",fee:"Retail",feat:"\u0110i\u1ec7n tho\u1ea1i, data bundles"},
{g:"Africa & ME",c:"Tanzania",f:"\u{1F1F9}\u{1F1FF}",r:"eastafrica",n:"Kikuu TZ",url:"kikuu.com",t:"marketplace",traffic:"~400K/mo",fee:"Cross-border",feat:"Ship t\u1eeb TQ gi\u00e1 r\u1ebb"},
{g:"Africa & ME",c:"Ethiopia",f:"\u{1F1EA}\u{1F1F9}",r:"eastafrica",n:"Jumia Ethiopia",url:"jumia.com.et",t:"marketplace",traffic:"~1.5M/mo",fee:"5-20%",feat:"Marketplace, COD"},
{g:"Africa & ME",c:"Ethiopia",f:"\u{1F1EA}\u{1F1F9}",r:"eastafrica",n:"Engocha",url:"engocha.com",t:"classified",traffic:"~800K/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"Classified Ethiopia"},
{g:"Africa & ME",c:"Ethiopia",f:"\u{1F1EA}\u{1F1F9}",r:"eastafrica",n:"Afromarket ET",url:"afromarket.et",t:"marketplace",traffic:"~300K/mo",fee:"Commission",feat:"Marketplace local"},
{g:"Africa & ME",c:"Ethiopia",f:"\u{1F1EA}\u{1F1F9}",r:"eastafrica",n:"Deliver Addis",url:"deliveraddis.com",t:"retail",traffic:"~400K/mo",fee:"Delivery",feat:"Grocery & food delivery Addis"},
{g:"Africa & ME",c:"Ethiopia",f:"\u{1F1EA}\u{1F1F9}",r:"eastafrica",n:"Shega Market",url:"shega.co",t:"marketplace",traffic:"~200K/mo",fee:"Directory",feat:"Business directory & e-commerce"},
{g:"Africa & ME",c:"Ethiopia",f:"\u{1F1EA}\u{1F1F9}",r:"eastafrica",n:"Addis Mercato",url:"addismercato.com",t:"marketplace",traffic:"~150K/mo",fee:"Commission",feat:"Named after famous market"},
{g:"Africa & ME",c:"Ethiopia",f:"\u{1F1EA}\u{1F1F9}",r:"eastafrica",n:"Ethioshare",url:"ethioshare.com",t:"classified",traffic:"~100K/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"Classified \u0111\u1ecba ph\u01b0\u01a1ng"},
{g:"Africa & ME",c:"Ethiopia",f:"\u{1F1EA}\u{1F1F9}",r:"eastafrica",n:"Gebeya",url:"gebeya.com",t:"marketplace",traffic:"~250K/mo",fee:"Marketplace",feat:"Tech talent & products"},
{g:"Africa & ME",c:"Ethiopia",f:"\u{1F1EA}\u{1F1F9}",r:"eastafrica",n:"AliExpress ET",url:"aliexpress.com",t:"marketplace",traffic:"~2M/mo (ET)",fee:"Cross-border",feat:"Cross-border ph\u1ed5 bi\u1ebfn"},
{g:"Africa & ME",c:"Ethiopia",f:"\u{1F1EA}\u{1F1F9}",r:"eastafrica",n:"Telegram Shops ET",url:"t.me",t:"marketplace",traffic:"~5M/mo",fee:"P2P mi\u1ec5n ph\u00ed",feat:"Telegram-based C2C r\u1ea5t ph\u1ed5 bi\u1ebfn"},
{g:"Africa & ME",c:"Uganda",f:"\u{1F1FA}\u{1F1EC}",r:"eastafrica",n:"Jumia Uganda",url:"jumia.ug",t:"marketplace",traffic:"~2M/mo",fee:"5-20%",feat:"Marketplace #1 Uganda"},
{g:"Africa & ME",c:"Uganda",f:"\u{1F1FA}\u{1F1EC}",r:"eastafrica",n:"Jiji Uganda",url:"jiji.ug",t:"classified",traffic:"~1.5M/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"Classified #1 Uganda, C2C"},
{g:"Africa & ME",c:"Uganda",f:"\u{1F1FA}\u{1F1EC}",r:"eastafrica",n:"Kilimall UG",url:"kilimall.ug",t:"marketplace",traffic:"~500K/mo",fee:"Commission",feat:"Cross-border marketplace"},
{g:"Africa & ME",c:"Uganda",f:"\u{1F1FA}\u{1F1EC}",r:"eastafrica",n:"SafeBoda Shop",url:"safeboda.com",t:"retail",traffic:"~400K/mo",fee:"Delivery",feat:"Ride-hailing + delivery"},
{g:"Africa & ME",c:"Uganda",f:"\u{1F1FA}\u{1F1EC}",r:"eastafrica",n:"Kikuu UG",url:"kikuu.com",t:"marketplace",traffic:"~300K/mo",fee:"Cross-border",feat:"Ship TQ gi\u00e1 r\u1ebb"},
{g:"Africa & ME",c:"Uganda",f:"\u{1F1FA}\u{1F1EC}",r:"eastafrica",n:"BuyHatke UG",url:"buyhatke.com",t:"marketplace",traffic:"~100K/mo",fee:"Price comparison",feat:"So s\u00e1nh gi\u00e1"},
{g:"Africa & ME",c:"Uganda",f:"\u{1F1FA}\u{1F1EC}",r:"eastafrica",n:"Catalog UG",url:"catalog.co.ug",t:"electronics",traffic:"~200K/mo",fee:"Retail",feat:"\u0110i\u1ec7n t\u1eed Uganda"},
{g:"Africa & ME",c:"Uganda",f:"\u{1F1FA}\u{1F1EC}",r:"eastafrica",n:"Glovo UG",url:"glovoapp.com/ug",t:"retail",traffic:"~300K/mo",fee:"Delivery",feat:"Multi-delivery"},
{g:"Africa & ME",c:"Uganda",f:"\u{1F1FA}\u{1F1EC}",r:"eastafrica",n:"Market.ug",url:"market.co.ug",t:"classified",traffic:"~150K/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"Rao v\u1eb7t Uganda"},
{g:"Africa & ME",c:"Uganda",f:"\u{1F1FA}\u{1F1EC}",r:"eastafrica",n:"Duka",url:"duka.ug",t:"marketplace",traffic:"~100K/mo",fee:"Commission",feat:"Marketplace local"},
{g:"Africa & ME",c:"Rwanda",f:"\u{1F1F7}\u{1F1FC}",r:"eastafrica",n:"Jumia Rwanda",url:"jumia.rw",t:"marketplace",traffic:"~500K/mo",fee:"5-20%",feat:"Marketplace Rwanda"},
{g:"Africa & ME",c:"Rwanda",f:"\u{1F1F7}\u{1F1FC}",r:"eastafrica",n:"VubaVuba",url:"vubavuba.rw",t:"retail",traffic:"~200K/mo",fee:"Delivery",feat:"Grocery & food delivery"},
{g:"Africa & ME",c:"Rwanda",f:"\u{1F1F7}\u{1F1FC}",r:"eastafrica",n:"HeHe Rwanda",url:"hehe.rw",t:"retail",traffic:"~150K/mo",fee:"Retail",feat:"Grocery online Kigali"},
{g:"Africa & ME",c:"Rwanda",f:"\u{1F1F7}\u{1F1FC}",r:"eastafrica",n:"Murukali",url:"murukali.com",t:"marketplace",traffic:"~100K/mo",fee:"Commission",feat:"Marketplace \u0111\u1ecba ph\u01b0\u01a1ng"},
{g:"Africa & ME",c:"Rwanda",f:"\u{1F1F7}\u{1F1FC}",r:"eastafrica",n:"OLX Rwanda",url:"olx.rw",t:"classified",traffic:"~80K/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"Classified C2C"},
{g:"Africa & ME",c:"Rwanda",f:"\u{1F1F7}\u{1F1FC}",r:"eastafrica",n:"Irembo Market",url:"irembo.gov.rw",t:"marketplace",traffic:"~300K/mo",fee:"Gov platform",feat:"E-gov + marketplace"},
{g:"Africa & ME",c:"Rwanda",f:"\u{1F1F7}\u{1F1FC}",r:"eastafrica",n:"Kikuu RW",url:"kikuu.com",t:"marketplace",traffic:"~100K/mo",fee:"Cross-border",feat:"Ship t\u1eeb TQ"},
{g:"Africa & ME",c:"Rwanda",f:"\u{1F1F7}\u{1F1FC}",r:"eastafrica",n:"Exuus",url:"exuus.com",t:"marketplace",traffic:"~50K/mo",fee:"Commission",feat:"Made in Rwanda products"},
{g:"Africa & ME",c:"Rwanda",f:"\u{1F1F7}\u{1F1FC}",r:"eastafrica",n:"Mergdata",url:"mergdata.com",t:"marketplace",traffic:"~40K/mo",fee:"Commission",feat:"AgriTech marketplace"},
{g:"Africa & ME",c:"Rwanda",f:"\u{1F1F7}\u{1F1FC}",r:"eastafrica",n:"AliExpress RW",url:"aliexpress.com",t:"marketplace",traffic:"~200K/mo (RW)",fee:"Cross-border",feat:"Mua h\u00e0ng qu\u1ed1c t\u1ebf"},
{g:"Africa & ME",c:"Ivory Coast",f:"\u{1F1E8}\u{1F1EE}",r:"westafrica",n:"Jumia C\u00f4te d'Ivoire",url:"jumia.ci",t:"marketplace",traffic:"~5M/mo",fee:"5-20%",feat:"Marketplace #1 CI, COD"},
{g:"Africa & ME",c:"Ivory Coast",f:"\u{1F1E8}\u{1F1EE}",r:"westafrica",n:"Afrimarket CI",url:"afrimarket.ci",t:"marketplace",traffic:"~1M/mo",fee:"Commission",feat:"Marketplace, diaspora remittance"},
{g:"Africa & ME",c:"Ivory Coast",f:"\u{1F1E8}\u{1F1EE}",r:"westafrica",n:"CoinAfrique CI",url:"coinafrique.com",t:"classified",traffic:"~2M/mo",fee:"Mi\u1ec5n ph\u00ed + boost",feat:"Classified #1 Francophone Africa"},
{g:"Africa & ME",c:"Ivory Coast",f:"\u{1F1E8}\u{1F1EE}",r:"westafrica",n:"Tonaton CI",url:"tonaton.ci",t:"classified",traffic:"~800K/mo",fee:"Mi\u1ec5n ph\u00ed",feat:"Classified C2C"},
{g:"Africa & ME",c:"Ivory Coast",f:"\u{1F1E8}\u{1F1EE}",r:"westafrica",n:"Yaatoo",url:"yaatoo.ci",t:"marketplace",traffic:"~300K/mo",fee:"Commission",feat:"Marketplace local"},
{g:"Africa & ME",c:"Ivory Coast",f:"\u{1F1E8}\u{1F1EE}",r:"westafrica",n:"Glovo CI",url:"glovoapp.com/ci",t:"retail",traffic:"~500K/mo",fee:"Delivery",feat:"Multi-delivery Abidjan"},
{g:"Africa & ME",c:"Ivory Coast",f:"\u{1F1E8}\u{1F1EE}",r:"westafrica",n:"Kikuu CI",url:"kikuu.com",t:"marketplace",traffic:"~400K/mo",fee:"Cross-border",feat:"Ship TQ gi\u00e1 r\u1ebb"},
{g:"Africa & ME",c:"Ivory Coast",f:"\u{1F1E8}\u{1F1EE}",r:"westafrica",n:"Orange Money Shop",url:"orange.ci",t:"marketplace",traffic:"~1.5M/mo",fee:"Mobile money",feat:"Mua s\u1eafm qua Orange Money"},
{g:"Africa & ME",c:"Ivory Coast",f:"\u{1F1E8}\u{1F1EE}",r:"westafrica",n:"AliExpress CI",url:"aliexpress.com",t:"marketplace",traffic:"~3M/mo (CI)",fee:"Cross-border",feat:"Ph\u1ed5 bi\u1ebfn, gi\u00e1 r\u1ebb"},
{g:"Africa & ME",c:"Ivory Coast",f:"\u{1F1E8}\u{1F1EE}",r:"westafrica",n:"Shein CI",url:"shein.com",t:"fashion",traffic:"~1M/mo (CI)",fee:"Cross-border",feat:"Fast fashion tr\u1ebb"},
  {g:"Africa & ME",c:"Saudi Arabia",f:"🇸🇦",r:"middleeast",n:"Amazon.sa",url:"amazon.sa",t:"retail",traffic:"~35M/mo",fee:"8-15% referral",feat:"Amazon Saudi, FBA, Arabic interface, Prime SA, $13B SA e-comm market"},
  {g:"Africa & ME",c:"Saudi Arabia",f:"🇸🇦",r:"middleeast",n:"Jarir Bookstore",url:"jarir.com",t:"retail",traffic:"~12M/mo",fee:"Direct retail",feat:"#1 SA electronics/books retailer, 70+ stores, online since 2001"},
  {g:"Africa & ME",c:"Saudi Arabia",f:"🇸🇦",r:"middleeast",n:"Extra Stores",url:"extrastores.com",t:"retail",traffic:"~5M/mo",fee:"Direct retail",feat:"Electronics/appliances SA, 50+ branches, competitive pricing"},
  {g:"Africa & ME",c:"Saudi Arabia",f:"🇸🇦",r:"middleeast",n:"Namshi",url:"namshi.com",t:"fashion",traffic:"~5M/mo",fee:"Commission varies",feat:"Fashion marketplace GCC, Noon-acquired, 1000+ brands, youth-focused"},
  {g:"Africa & ME",c:"UAE",f:"🇦🇪",r:"middleeast",n:"SharafDG",url:"sharafdg.com",t:"retail",traffic:"~3M/mo",fee:"Direct retail",feat:"Electronics retailer UAE, 20+ stores, online marketplace, Apple authorized"},
  {g:"Africa & ME",c:"UAE",f:"🇦🇪",r:"middleeast",n:"Mumzworld",url:"mumzworld.com",t:"retail",traffic:"~2M/mo",fee:"Direct retail",feat:"Baby/kids marketplace MENA, 200K+ products, mama community"},
  {g:"Africa & ME",c:"UAE",f:"🇦🇪",r:"middleeast",n:"Dubizzle",url:"dubizzle.com",t:"classified",traffic:"~15M/mo",fee:"Free private / paid features",feat:"#1 UAE classifieds, EMPG/OLX Group, cars/property/jobs/goods"},
  {g:"Africa & ME",c:"UAE",f:"🇦🇪",r:"middleeast",n:"Amazon.ae",url:"amazon.ae",t:"retail",traffic:"~25M/mo",fee:"8-15% referral",feat:"Amazon UAE (ex-Souq.com), FBA, Prime, leading GCC marketplace"},
  {g:"Africa & ME",c:"Qatar",f:"🇶🇦",r:"middleeast",n:"Snoonu Market",url:"snoonu.com",t:"retail",traffic:"~1M/mo",fee:"Varies",feat:"Super app QA, grocery/food/shopping delivery, Qatari startup"},
  {g:"Africa & ME",c:"Bahrain",f:"🇧🇭",r:"middleeast",n:"Noon BH",url:"noon.com",t:"retail",traffic:"~2M/mo (BH)",fee:"5-20% commission",feat:"Noon marketplace in Bahrain, Emaar-backed, Noon Express"},
  {g:"Africa & ME",c:"Kuwait",f:"🇰🇼",r:"middleeast",n:"Opensooq KW",url:"opensooq.com",t:"classified",traffic:"~3M/mo",fee:"Free private",feat:"Classifieds KW, cars/property/electronics, Arabic-first"},
  {g:"Africa & ME",c:"Oman",f:"🇴🇲",r:"middleeast",n:"Opensooq OM",url:"opensooq.com",t:"classified",traffic:"~1M/mo",fee:"Free private",feat:"Classifieds OM, all categories"},
  {g:"Africa & ME",c:"Jordan",f:"🇯🇴",r:"middleeast",n:"OpenSooq JO",url:"opensooq.com",t:"classified",traffic:"~5M/mo",fee:"Free private",feat:"#1 JO classifieds, 500K+ monthly ads, cars/property/jobs"},
  {g:"Africa & ME",c:"Jordan",f:"🇯🇴",r:"middleeast",n:"MarkaVIP",url:"markavip.com",t:"fashion",traffic:"~1M/mo",fee:"Flash sales model",feat:"Fashion flash sales MENA, Jabbar Group, designer brands"},
  {g:"Africa & ME",c:"Egypt",f:"🇪🇬",r:"northafrica",n:"Amazon.eg",url:"amazon.eg",t:"retail",traffic:"~15M/mo",fee:"8-15% referral",feat:"Amazon Egypt (ex-Souq), FBA, Arabic, Prime EG, biggest MENA e-comm market"},
  {g:"Africa & ME",c:"Egypt",f:"🇪🇬",r:"northafrica",n:"B.Tech",url:"btech.com",t:"retail",traffic:"~5M/mo",fee:"Direct retail",feat:"#1 EG electronics retailer, 100+ stores, installment plans"},
  {g:"Africa & ME",c:"Egypt",f:"🇪🇬",r:"northafrica",n:"OLX Egypt",url:"olx.com.eg",t:"classified",traffic:"~12M/mo",fee:"Free private",feat:"#1 EG classifieds, cars/property/electronics, 5M+ monthly ads"},
  {g:"Africa & ME",c:"Egypt",f:"🇪🇬",r:"northafrica",n:"Noon Egypt",url:"noon.com",t:"retail",traffic:"~8M/mo (EG)",fee:"5-20% commission",feat:"Noon marketplace EG, express delivery, Arabic-first, Noon Minutes grocery"},
  {g:"Africa & ME",c:"Morocco",f:"🇲🇦",r:"northafrica",n:"Avito.ma",url:"avito.ma",t:"classified",traffic:"~15M/mo",fee:"Free private / paid features",feat:"#1 MA classifieds, OLX/Frontier group, 10M+ users, cars/property/goods"},
  {g:"Africa & ME",c:"Morocco",f:"🇲🇦",r:"northafrica",n:"Hmall.ma",url:"hmall.ma",t:"retail",traffic:"~1M/mo",fee:"Varies",feat:"E-commerce marketplace MA, local products, growing adoption"},
  {g:"Africa & ME",c:"Tunisia",f:"🇹🇳",r:"northafrica",n:"Tayara.tn",url:"tayara.tn",t:"classified",traffic:"~5M/mo",fee:"Free private / featured",feat:"#1 TN classifieds, 2M+ ads, cars/property/electronics/jobs"},
  {g:"Africa & ME",c:"Algeria",f:"🇩🇿",r:"northafrica",n:"Ouedkniss",url:"ouedkniss.com",t:"classified",traffic:"~15M/mo",fee:"Free private",feat:"#1 DZ classifieds, 3M+ daily visits, cars/electronics/property, Arabic/French"},
  {g:"Africa & ME",c:"South Africa",f:"🇿🇦",r:"subsaharan",n:"Bidorbuy",url:"bidorbuy.co.za",t:"marketplace",traffic:"~3M/mo",fee:"5-12% final value",feat:"SA marketplace, auction + fixed, 7M+ products, since 1999"},
  {g:"Africa & ME",c:"South Africa",f:"🇿🇦",r:"subsaharan",n:"Superbalist",url:"superbalist.com",t:"fashion",traffic:"~3M/mo",fee:"Varies",feat:"Fashion marketplace ZA, Takealot Group, curated brands, SA lifestyle"},
  {g:"Africa & ME",c:"South Africa",f:"🇿🇦",r:"subsaharan",n:"Makro",url:"makro.co.za",t:"retail",traffic:"~5M/mo",fee:"Direct retail",feat:"Wholesale/retail ZA, Massmart/Walmart Group, electronics/groceries"},
  {g:"Africa & ME",c:"South Africa",f:"🇿🇦",r:"subsaharan",n:"Bob Shop (Loot)",url:"bobshop.co.za",t:"retail",traffic:"~2M/mo",fee:"Direct retail",feat:"Online retailer ZA, ex-Loot.co.za, electronics/books/toys"},
  {g:"Africa & ME",c:"Nigeria",f:"🇳🇬",r:"subsaharan",n:"Jiji Nigeria",url:"jiji.ng",t:"classified",traffic:"~10M/mo",fee:"Free private / paid promo",feat:"#1 NG classifieds (acquired OLX NG), cars/phones/fashion, 12M+ monthly"},
  {g:"Africa & ME",c:"Ghana",f:"🇬🇭",r:"subsaharan",n:"Jiji Ghana",url:"jiji.com.gh",t:"classified",traffic:"~3M/mo",fee:"Free private",feat:"#1 GH classifieds, (acquired Tonaton), all categories"},
  {g:"Africa & ME",c:"Tanzania",f:"🇹🇿",r:"subsaharan",n:"Jiji Tanzania",url:"jiji.co.tz",t:"classified",traffic:"~2M/mo",fee:"Free private",feat:"Leading TZ classifieds, mobile-first, cars/phones/property"},
  {g:"Africa & ME",c:"Ethiopia",f:"🇪🇹",r:"subsaharan",n:"Engocha",url:"engocha.com",t:"classified",traffic:"~500K/mo",fee:"Free private",feat:"Growing ET e-commerce, classifieds, local marketplace"},
  {g:"Africa & ME",c:"Uganda",f:"🇺🇬",r:"subsaharan",n:"Jiji Uganda",url:"jiji.ug",t:"classified",traffic:"~1M/mo",fee:"Free private",feat:"Leading UG classifieds, Jiji Group expansion"},
  {g:"Africa & ME",c:"Rwanda",f:"🇷🇼",r:"subsaharan",n:"HeHe",url:"hfrwanda.com",t:"retail",traffic:"~200K/mo",fee:"Varies",feat:"E-commerce RW, groceries/electronics, Kigali delivery"},
  {g:"Africa & ME",c:"Senegal",f:"🇸🇳",r:"subsaharan",n:"Afrikrea",url:"afrikrea.com",t:"fashion",traffic:"~500K/mo",fee:"10-15%",feat:"African fashion marketplace, handmade/Ankara, pan-African, 10K+ designers"},
  {g:"Africa & ME",c:"Côte d'Ivoire",f:"🇨🇮",r:"subsaharan",n:"Jumia CI",url:"jumia.ci",t:"marketplace",traffic:"~1M/mo",fee:"5-20%",feat:"Leading CI marketplace, Jumia Group, electronics/fashion/groceries"},
  {g:"Africa & ME",c:"Cameroon",f:"🇨🇲",r:"subsaharan",n:"Jumia CM",url:"jumia.cm",t:"marketplace",traffic:"~500K/mo",fee:"5-20%",feat:"E-commerce CM, Jumia Group, COD payments, growing adoption"},
  {g:"Africa & ME",c:"Israel",f:"🇮🇱",r:"middleeast",n:"Zap.co.il",url:"zap.co.il",t:"marketplace",traffic:"~12M/mo",fee:"CPC model",feat:"#1 IL price comparison + marketplace, 10K+ shops, reviews"},
  {g:"Africa & ME",c:"Israel",f:"🇮🇱",r:"middleeast",n:"Yad2",url:"yad2.co.il",t:"classified",traffic:"~20M/mo",fee:"Free private / paid features",feat:"#1 IL classifieds, cars/property/goods, Axel Springer-owned"},
  {g:"Africa & ME",c:"South Africa",f:"🇿🇦",r:"subsaharan",n:"OLX South Africa",url:"olx.co.za",t:"classified",traffic:"~5M/mo",fee:"Free private",feat:"ZA classifieds, Naspers/OLX Group, cars/property/electronics"},
  {g:"Africa & ME",c:"Kenya",f:"🇰🇪",r:"subsaharan",n:"Jiji Kenya",url:"jiji.co.ke",t:"classified",traffic:"~3M/mo",fee:"Free private",feat:"Growing KE classifieds, Jiji Group, mobile-first"},
  {g:"Africa & ME",c:"Kenya",f:"🇰🇪",r:"subsaharan",n:"Kilimall",url:"kilimall.co.ke",t:"marketplace",traffic:"~1M/mo",fee:"5-15%",feat:"KE marketplace, Chinese-backed, electronics/fashion, expanding East Africa"},
  {g:"Africa & ME",c:"Morocco",f:"🇲🇦",r:"northafrica",n:"Jumia Morocco",url:"jumia.ma",t:"marketplace",traffic:"~3M/mo",fee:"5-20%",feat:"Leading MA marketplace, Jumia Group, electronics/fashion/beauty"},
  {g:"Africa & ME",c:"Egypt",f:"🇪🇬",r:"northafrica",n:"Jumia Egypt",url:"jumia.com.eg",t:"marketplace",traffic:"~5M/mo",fee:"5-20%",feat:"Major EG marketplace, Jumia Group, electronics/fashion, JumiaPay"},
  {g:"Africa & ME",c:"Ghana",f:"🇬🇭",r:"subsaharan",n:"Jumia Ghana",url:"jumia.com.gh",t:"marketplace",traffic:"~1M/mo",fee:"5-20%",feat:"GH marketplace, Jumia Group, electronics/fashion/phones"},
  {g:"Africa & ME",c:"Senegal",f:"🇸🇳",r:"subsaharan",n:"Expat-Dakar",url:"expat-dakar.com",t:"classified",traffic:"~2M/mo",fee:"Free private",feat:"#1 SN classifieds, property/cars/electronics, French language"},
  {g:"Africa & ME",c:"Pakistan",f:"🇵🇰",r:"middleeast",n:"PakWheels",url:"pakwheels.com",t:"classified",traffic:"~8M/mo",fee:"Listing fees vary",feat:"#1 PK auto marketplace, cars/bikes/parts, reviews, price calculator"},
  {g:"Africa & ME",c:"Iran",f:"🇮🇷",r:"middleeast",n:"Divar",url:"divar.ir",t:"classified",traffic:"~50M/mo",fee:"Free private / promoted",feat:"#1 IR classifieds, 40M+ MAU, cars/property/electronics, Persian"},
  {g:"Africa & ME",c:"Iran",f:"🇮🇷",r:"middleeast",n:"Digikala",url:"digikala.com",t:"marketplace",traffic:"~60M/mo",fee:"8-20%",feat:"#1 IR e-commerce, 40M+ products, DigiPay, logistics network, IPO candidate"},
  {g:"Africa & ME",c:"Libya",f:"🇱🇾",r:"northafrica",n:"Opensooq LY",url:"opensooq.com",t:"classified",traffic:"~1M/mo",fee:"Free private",feat:"Classifieds LY, cars/property/electronics"},
  {g:"Africa & ME",c:"Sudan",f:"🇸🇩",r:"northafrica",n:"Opensooq SD",url:"opensooq.com",t:"classified",traffic:"~500K/mo",fee:"Free private",feat:"Classifieds SD, mobile-first, Arabic"},
  {g:"Africa & ME",c:"Tanzania",f:"🇹🇿",r:"subsaharan",n:"Jumia Tanzania",url:"jumia.co.tz",t:"marketplace",traffic:"~500K/mo",fee:"5-20%",feat:"TZ marketplace, Jumia Group, mobile-first, COD"},
  {g:"Africa & ME",c:"Uganda",f:"🇺🇬",r:"subsaharan",n:"Jumia Uganda",url:"jumia.ug",t:"marketplace",traffic:"~500K/mo",fee:"5-20%",feat:"UG marketplace, Jumia Group, growing mobile commerce"}
];